version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - phpfpm
    networks:
      web_app_net:
        ipv4_address: 192.168.0.2

  phpfpm:
    container_name: phpfpm
    build: ./phpfpm
    volumes:
     - ./laravel_app:/var/www/laravel_app
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - mariadb
    networks:
      web_app_net:
        ipv4_address: 192.168.0.3

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/data:/var/lib/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: web_app
      MYSQL_USER: web_app
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    networks:
      web_app_net:
        ipv4_address: 192.168.0.4

  api:
    container_name: api
    build: ./api
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - ./api:/go/src/api
    depends_on:
      - mariadb
    networks:
      web_app_net:
        ipv4_address: 192.168.0.5

  packet_capture:
    container_name: packet_capture
    build: ./packet_capture
    ports:
      - "4000:4000"
    tty: true
    volumes:
      - ./packet_capture:/go/src/packet_capture
    depends_on:
      - mariadb
    networks:
      web_app_net:
        ipv4_address: 192.168.0.6

networks:
  web_app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
