version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - phpfpm

  phpfpm:
    container_name: phpfpm
    build: ./phpfpm
    volumes:
     - .:/var/www/
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/data:/var/lib/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel_app
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo

  golang:
    container_name: golang
    build: ./golang
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - ./golang:/go/src/api
    depends_on:
      - mariadb
